#!/bin/sh

mount -t proc proc /proc

mknod -m 666 /dev/null c 1 3
mknod -m 666 /dev/zero c 1 5
mknod -m 666 /dev/full c 1 7
mknod -m 666 /dev/random c 1 8
mknod -m 666 /dev/urandom c 1 9
mknod -m 600 /dev/kmsg c 1 11
mknod -m 620 /dev/tty0 c 4 0
mknod -m 620 /dev/ttyS0 c 4 64

/bin/sh
